<?php

use App\Shop\Products\Product;
use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    public function run()
    {
        factory(Product::class)->create();

        \DB::table('products')->insert([
            //laptops
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'Lenovo IdeaPad 3 14Inch Laptop',
'slug' => 'Lenovo-IdeaPad-3-14Inch-Laptop',
'description' => 'Lenovo IdeaPad 3 14Inch Laptop- 14.0Inch FHD (1920 x 1080) Display- AMD Ryzen 5 3500U Processor- 8GB DDR4 RAM- 256GB SSD- AMD Radeon Vega 8 Graphics- Narrow Bezel- Windows 10- 81W0003QUS- Abyss Blue',
'cover' => 'products/lenovo1.png',
'quantity' => 10,
'price' => 518.88,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
    [
    'brand_id' => null,
    'sku' => mt_rand(1000000, 9999999),
    'name' => '2020 Newest HP ENVY x360 2-in-1 Laptop',
    'slug' => '2020 Newest HP ENVY x360 2-in-1 Laptop',
    'description' => '2020 Newest HP ENVY x360 2-in-1 Laptop- 15.6Inch Full HD Touchscreen- AMD Ryzen 5 4500U Processor up to 4.0GHz- 8GB Memory- 256GB PCIe SSD- Backlit Keyboard- HDMI- Wi-Fi- Windows 10 Home- Nightfall Black',
    'cover' => 'products/hp2.jpg',
    'quantity' => 10,
    'price' => 719.00,
    'sale_price' => null,
    'status' => 1,
    'length' => null,
    'width' => null,
    'height' => null,
    'distance_unit' => '',
    'weight' => 400,
    'mass_unit' => 'gms',
    'created_at' => date('Y-m-d H:i:s'),
    'updated_at' => date('Y-m-d H:i:s'),
    ],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'Acer Predator Helios 300 Gaming Laptop',
'slug' => 'Acer Predator Helios 300 Gaming Laptop',
'description' => 'Acer Predator Helios 300 Gaming Laptop- Intel i7-10750H- NVIDIA GeForce RTX 2060 6GB- 15.6Inch Full HD 144Hz 3ms IPS Display- 16GB Dual-Channel DDR4- 512GB NVMe SSD- Wi-Fi 6- RGB Keyboard- PH315-53-72XD',
'cover' => 'products/acer1.png',
'quantity' => 10,
'price' => 1179.38,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'Lenovo Chromebook Flex 5 13Inch Laptop',
'slug' => 'Lenovo Chromebook Flex 5 13Inch Laptop',
'description' => 'Lenovo Chromebook Flex 5 13Inch Laptop- FHD (1920 x 1080) Touch Display- Intel Core i3-10110U Processor- 4GB DDR4 OnBoard RAM- 64GB SSD- Intel Integrated Graphics- Chrome OS- 82B80006UX- Graphite Grey',
'cover' => 'products/lenovo2.jpg',
'quantity' => 10,
'price' => 409.99,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'Acer Swift 3 Thin & Light Laptop',
'slug' => 'Acer Swift 3 Thin & Light Laptop',
'description' => 'Acer Swift 3 Thin & Light Laptop- 14Inch Full HD IPS- AMD Ryzen 7 4700U Octa-Core with Radeon Graphics- 8GB LPDDR4- 512GB NVMe SSD- Wi-Fi 6- Backlit KB- Fingerprint Reader- Alexa Built-in- SF314-42-R9YN',
'cover' => 'products/acer2.jpg',
'quantity' => 10,
'price' => 679.99,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'ASUS UX534FTC-AS77 ZenBook 15 Laptop',
'slug' => 'ASUS UX534FTC-AS77 ZenBook 15 Laptop',
'description' => 'ASUS UX534FTC-AS77 ZenBook 15 Laptop- 15.6” UHD 4K NanoEdge Display- Intel Core i7-10510U- GeForce GTX 1650- 16GB- 512GB PCIe SSD- ScreenPad 2.0- Amazon Alexa Compatible- Windows 10- Icicle Silver',
'cover' => 'products/asus1.jpg',
'quantity' => 10,
'price' => 1166.23,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'Acer Chromebook Spin 11 CP311-1H-C5PN Convertible Laptop',
'slug' => 'Acer Chromebook Spin 11 CP311-1H-C5PN Convertible Laptop',
'description' => 'Acer Chromebook Spin 11 CP311-1H-C5PN Convertible Laptop- Celeron N3350- 11.6Inch HD Touch- 4GB DDR4- 32GB eMMC- Google Chrome',
'cover' => 'products/acer3.jpg',
'quantity' => 10,
'price' => 373.00,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'ASUS F512JA-AS34 VivoBook 15 Thin And Light Laptop',
'slug' => 'ASUS F512JA-AS34 VivoBook 15 Thin And Light Laptop',
'description' => 'ASUS F512JA-AS34 VivoBook 15 Thin And Light Laptop- 15.6” FHD Display- Intel i3-1005G1 CPU- 8GB RAM- 128GB SSD- Backlit Keyboard- Fingerprint- Windows 10 Home in S Mode- Slate Gray',
'cover' => 'products/asus2.jpg',
'quantity' => 10,
'price' => 469.00,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'Acer Aspire TC-885-UA92 Desktop',
'slug' => 'Acer Aspire TC-885-UA92 Desktop',
'description' => 'Acer Aspire TC-885-UA92 Desktop- 9th Gen Intel Core i5-9400- 12GB DDR4- 512GB SSD- 8X DVD- 802.11AC Wifi- USB 3.1 Type C- Windows 10 Home- Black',
'cover' => 'products/acer4.jpg',
'quantity' => 10,
'price' => 639.00,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'ASUS ROG GU502GW-AH76 Zephyrus M Thin and Portable Gaming Laptop',
'slug' => 'ASUS ROG GU502GW-AH76 Zephyrus M Thin and Portable Gaming Laptop',
'description' => 'ASUS ROG GU502GW-AH76 Zephyrus M Thin and Portable Gaming Laptop- 15.6” 240Hz FHD IPS- NVIDIA GeForce RTX 2070- Intel Core i7-9750H- 16GB DDR4 RAM- 1TB PCIe SSD- Per-Key RGB- Windows 10 Home',
'cover' => 'products/asus3.jpg',
'quantity' => 10,
'price' => 1688.35,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'NEW Microsoft Surface Go 2',
'slug' => 'NEW Microsoft Surface Go 2',
'description' => 'NEW Microsoft Surface Go 2 - 10.5Inch Touch-Screen - Intel Pentium - 4GB Memory - 64GB - Wifi - Platinum (Latest Model)',
'cover' => 'products/surface1.jpg',
'quantity' => 10,
'price' => 549.99,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'iBUYPOWER Gaming PC Computer Desktop Element Mini 9300',
'slug' => 'iBUYPOWER Gaming PC Computer Desktop Element Mini 9300',
'description' => 'iBUYPOWER Gaming PC Computer Desktop Element Mini 9300 (AMD Ryzen 3 3100 3.6GHz- AMD Radeon RX 550 2GB- 8GB DDR4 RAM- 240GB SSD- WiFi Ready- Windows 10 Home)',
'cover' => 'products/ibuypower1.jpg',
'quantity' => 10,
'price' => 549.99,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'HP 22-inch All-in-One Desktop',
'slug' => 'HP 22-inch All-in-One Desktop',
'description' => 'HP 22-inch All-in-One Desktop Computer- AMD Athlon Silver 3050U Processor- 4 GB RAM- 256 GB SSD- Windows 10 Home (22-dd0010- White)- Snow White',
'cover' => 'products/hp1.jpg',
'quantity' => 10,
'price' => 499.00,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],

// smart home
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'Smart Plug',
'slug' => 'Smart Plug',
'description' => 'Smart Plug works with Alexa to add voice control to any outlet.
Certified for Humans - Struggle-free- tinker-free- stress-free. No patience needed—its actually simple.',
'cover' => 'products/smart-plug.jpg',
'quantity' => 10,
'price' => 24.99,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'Hive Heating and Cooling Smart Thermostat Pack',
'slug' => 'Hive Heating and Cooling Smart Thermostat Pack',
'description' => 'Hive Heating and Cooling Smart Thermostat Pack- Thermostat + Hive Hub- Works with Alexa & Google Home- Requires C-Wire',
'cover' => 'products/have-healthing.jpg',
'quantity' => 10,
'price' => 173.78,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'Echo Dot (3rd Gen)',
'slug' => 'Echo Dot (3rd Gen)',
'description' => 'Echo Dot (3rd Gen) - Smart speaker with Alexa - Sandstone',
'cover' => 'products/echo-dot.jpg',
'quantity' => 10,
'price' => 39.99,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'Ring Alarm Smoke and CO Listener',
'slug' => 'Ring Alarm Smoke and CO Listener',
'description' => 'Ring Alarm Smoke and CO Listener alerts you on your smart phone when your existing smoke and carbon monoxide detectors sound their alarms.',
'cover' => 'products/ring-alarm.jpg',
'quantity' => 10,
'price' => 34.99,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'Google- T3008US- Nest Learning Thermostat',
'slug' => 'Google- T3008US- Nest Learning Thermostat',
'description' => 'Google- T3008US- Nest Learning Thermostat- 3rd Gen- Smart Thermostat- Pro Version- Works With Alexa',
'cover' => 'products/nest-learning-thermostat.jpg',
'quantity' => 10,
'price' => 226.90,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'Schlage Z-Wave Connect Camelot Touchscreen Deadbolt with Built-In Alarm- Satin Nickel- BE469 CAM 619',
'slug' => 'Schlage Z-Wave Connect Camelot Touchscreen Deadbolt with Built-In Alarm- Satin Nickel- BE469 CAM 619',
'description' => 'Works with Alexa for voice control (hub required- Alexa device and hub sold separately)
Touch Screen keypad and lock cylinder on exterior and thumb turn interior. Door thickness range is 1.37 to 1.75 standard',
'cover' => 'products/schlage-z.jpg',
'quantity' => 10,
'price' => 223.99,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],

// Furniture
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'FURINNO Efficient Home',
'slug' => 'FURINNO Efficient Home',
'description' => 'FURINNO Efficient Home Laptop Notebook Computer Desk- Square Side Shelves- French Oak Grey/Black',
'cover' => 'products/furinno1.jpg',
'quantity' => 10,
'price' => 61.79,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'FITUEYES Universal TV',
'slug' => 'FITUEYES Universal TV',
'description' => 'FITUEYES Universal TV Stand Table Top TV Stand for 27-55 inch LCD LED TVs 6 Level Height Adjustable TV Base with Tempered Glass Base VESA 400x400 Holds up to 88lbs TT103701GB',
'cover' => 'products/fitueyes.jpg',
'quantity' => 10,
'price' => 23.99,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'Office Chair',
'slug' => 'Office Chair',
'description' => 'Office Chair- Mid Back Mesh Office Computer Swivel Desk Task Chair- Ergonomic Executive Chair with Armrests',
'cover' => 'products/office-chair.jpg',
'quantity' => 10,
'price' => 79.99,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'FURINNO Andrey End Table Nightstand Set',
'slug' => 'FURINNO Andrey End Table Nightstand Set',
'description' => 'FURINNO Andrey End Table Nightstand Set- 2-Pack- French Oak Grey',
'cover' => 'products/furinno2.jpg',
'quantity' => 10,
'price' => 40.00,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'Lorell File Cabinet',
'slug' => 'Lorell File Cabinet',
'description' => 'Plastic100% Imported Accommodates letter-size hanging files Designed with stylish embossed drawer fronts and easy roll casters. Product Dimensions are 14.3InchWIDTH x 18InchDEPTH x 24.5Inch HEIGHT',
'cover' => 'products/lorell-file-cabinet.jpg',
'quantity' => 10,
'price' => 73.99,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'Winsome Halifax',
'slug' => 'Winsome Halifax',
'description' => 'Winsome Halifax Storage/Organization- 5 Drawer- White',
'cover' => 'products/winsome-halifax.jpg',
'quantity' => 10,
'price' => 96.54,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'Linon Home Decor Tray Table Set',
'slug' => 'Linon Home Decor Tray Table Set',
'description' => 'Brown Faux Marble Seat includes Tray Tables and Storage Stand Easy to move from one room to another with the handle on top A home furnishing staple Set in stand is 19Inchw x 13Inchd x 31Inchh Individual tray',
'cover' => 'products/table.jpg',
'quantity' => 10,
'price' => 63.10,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'Vibe 12-Inch Gel Memory Foam Mattress | Bed in a Box',
'slug' => 'Vibe 12-Inch Gel Memory Foam Mattress | Bed in a Box',
'description' => 'Vibe 12-Inch Gel Memory Foam Mattress | Bed in a Box- (Mattress Only)- Twin XL',
'cover' => 'products/bed.jpg',
'quantity' => 10,
'price' => 155.97,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'Humble Crew Kids Book Rack Storage Bookshelf',
'slug' => 'Humble Crew Kids Book Rack Storage Bookshelf',
'description' => 'Nylon Toddler-sized bookshelf Displays books making it easy for kids to identify and grab books 4 deep- fabric sling sleeves hold books of almost any size Promotes organization and reading skills for Girls and boys',
'cover' => 'products/humble-crew-kids-book.png',
'quantity' => 10,
'price' => 33.96,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'CubiCubi Computer Office Small Desk 47Inch',
'slug' => 'CubiCubi Computer Office Small Desk 47Inch',
'description' => 'CubiCubi Computer Office Small Desk 47Inch- Study Writing Table- Modern Simple Style PC Desk with Splice Board- Black and Rustic Brown',
'cover' => 'products/computer-office1.png',
'quantity' => 10,
'price' => 119.99,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'LUCID 5 Inch Memory Foam Low Profile-Cooling Gel',
'slug' => 'LUCID 5 Inch Memory Foam Low Profile-Cooling Gel',
'description' => 'LUCID 5 Inch Memory Foam Low Profile-Cooling Gel Infusion-Hypoallergenic Bamboo Charcoal-Breathable Cover Bed Mattress Conventional- Twin- WHITE',
'cover' => 'products/lucid5.jpg',
'quantity' => 10,
'price' => 99.99,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
30=> [
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'Walker Edison Furniture',
'slug' => 'Walker Edison Furniture',
'description' => 'Walker Edison Furniture Company Modern Corner L Shaped Glass Computer Writing Gaming Gamer Command Center Workstation Desk Home Office- Single- Black',
'cover' => 'products/walker-edison.jpg',
'quantity' => 10,
'price' => 135.72,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'Amazon Brand – Rivet Malida',
'slug' => 'Amazon Brand – Rivet Malida',
'description' => 'Amazon Brand – Rivet Malida Mid-Century Modern Open Back Kitchen Dining Room Accent Chair- 33InchH- Aqua',
'cover' => 'products/amazon-brand.jpg',
'quantity' => 10,
'price' => 215.42,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],

// Cell Phones & Accessories

[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'Google Pixel 4a',
'slug' => 'Google Pixel 4a',
'description' => 'Google Pixel 4a - New Unlocked Android Smartphone - 128 GB of Storage - Up to 24 Hour Battery - Just Black',
'cover' => 'products/google-pixel.jpg',
'quantity' => 10,
'price' => 349.99,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'TOZO T6 True Wireless Earbuds Bluetooth',
'slug' => 'TOZO T6 True Wireless Earbuds Bluetooth',
'description' => 'TOZO T6 True Wireless Earbuds Bluetooth Headphones Touch Control with Wireless Charging Case IPX8 Waterproof TWS Stereo Earphones in-Ear Built-in Mic Headset Premium Deep Bass for Sport Black',
'cover' => 'products/earbuds1.jpg',
'quantity' => 10,
'price' =>39.99,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'SAMSUNG: EVO Select 128GB microSDXC',
'slug' => 'SAMSUNG: EVO Select 128GB microSDXC',
'description' => 'SAMSUNG: EVO Select 128GB microSDXC UHS-I U3 100MB/s Full HD & 4K UHD Memory Card with Adapter (MB-ME128HA)',
'cover' => 'products/microsdxc.jpg',
'quantity' => 10,
'price' => 19.99,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'Samsung Galaxy Buds+ Plus',
'slug' => 'Samsung Galaxy Buds+ Plus',
'description' => 'Samsung Galaxy Buds+ Plus- True Wireless Earbuds (Wireless Charging Case included)- Black – US Version',
'cover' => 'products/earbuds2.jpg',
'quantity' => 10,
'price' => 129.99,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'HOVAMP iPhone Charger',
'slug' => 'HOVAMP iPhone Charger',
'description' => 'HOVAMP iPhone Charger- MFi Certified Lightning Cable 5 Pack (3/3/6/6/10FT) Nylon Woven with Metal Connector Compatible iPhone 11/Pro/Xs Max/X/8/7/Plus/6S/6/SE/5S iPad - Silver&White',
'cover' => 'products/iphone-charger.jpg',
'quantity' => 10,
'price' => 10.99,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'Sony WH-1000XM4 Wireless',
'slug' => 'Sony WH-1000XM4 Wireless',
'description' => 'Sony WH-1000XM4 Wireless Industry Leading Noise Canceling Overhead Headphones with Mic for phone-call and Alexa voice control- Black',
'cover' => 'products/sony-casq.jpg',
'quantity' => 10,
'price' => 348.00,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'Updated 2020 Watch Charger',
'slug' => 'Updated 2020 Watch Charger',
'description' => 'Updated 2020 Watch Charger- Powlaken Charging Cable MFi Certified Magnetic Wireless Portable Charger Charging Cable Cord Compatible for Apple Watch SE Apple Watch Series 6 5 4 3 2 1',
'cover' => 'products/watch-charger.png',
'quantity' => 10,
'price' => 11.95,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'Fitbit Versa 2',
'slug' => 'Fitbit Versa 2',
'description' => 'Fitbit Versa 2 Health and Fitness Smartwatch with Heart Rate- Music- Alexa Built-In- Sleep and Swim Tracking- Black/Carbon- One Size (S and L Bands Included)',
'cover' => 'products/fitbit-versa-2.jpg',
'quantity' => 10,
'price' => 178.95,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'Samsung Galaxy S20 FE 5G',
'slug' => 'Samsung Galaxy S20 FE 5G',
'description' => 'Samsung Galaxy S20 FE 5G | Factory Unlocked Android Cell Phone | 128 GB | US Version Smartphone | Pro-Grade Camera- 30X Space Zoom- Night Mode | Cloud Navy',
'cover' => 'products/S20.jpg',
'quantity' => 10,
'price' => 599.99,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'Samsung Galaxy Note 10+',
'slug' => 'Samsung Galaxy Note 10+',
'description' => 'Samsung Galaxy Note 10+ Plus Factory Unlocked Cell Phone with 256GB (U.S. Warranty)- Aura White/ Note10+',
'cover' => 'products/Samsung-Galaxy-Note-10.jpg',
'quantity' => 10,
'price' => 1099.99,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s'),
],
[
'brand_id' => null,
'sku' => mt_rand(1000000, 9999999),
'name' => 'Chargers- Pantom 2-Pack',
'slug' => 'Chargers- Pantom 2-Pack',
'description' => 'Chargers- Pantom 2-Pack Charging Adapter Travel Wall Chargers with 2-Pack 5-FeetLightning Cables Charge Sync for iPhone X- iPhone 8- iPhone 7- iPhone 6- iPhone 5- iPad Mini',
'cover' => 'products/pantom-2-pack.jpg',
'quantity' => 10,
'price' => 15.95,
'sale_price' => null,
'status' => 1,
'length' => null,
'width' => null,
'height' => null,
'distance_unit' => '',
'weight' => 400,
'mass_unit' => 'gms',
'created_at' => date('Y-m-d H:i:s'),
'updated_at' => date('Y-m-d H:i:s')
]
        ]);


        \DB::table('category_product')->insert([
            [
                    'category_id' => 6,
                    'product_id' => 18,
                ],
            [
                'category_id' => 6,
                'product_id' => 19,
            ],
        [
                    'category_id' => 6,
                    'product_id' => 20,
                ],
        [
                    'category_id' => 6,
                    'product_id' => 21,
                ],
        [
                    'category_id' => 6,
                    'product_id' => 22,
                ],
        [
                    'category_id' => 6,
                    'product_id' => 23,
                ],
        [
                    'category_id' => 6,
                    'product_id' => 24,
                ],
        [
                    'category_id' => 6,
                    'product_id' => 25,
                ],
        [
                    'category_id' => 6,
                    'product_id' => 26,
                ],
        [
                    'category_id' => 6,
                    'product_id' => 27,
                ],
        [
                    'category_id' => 6,
                    'product_id' => 28,
                ],
            [
                    'category_id' => 6,
                    'product_id' => 29,
                ],
            [
                    'category_id' => 6,
                    'product_id' => 30,
                ],
                //smart home
            [
                    'category_id' => 7,
                    'product_id' => 31,
                ],
            [
                    'category_id' => 7,
                    'product_id' => 32,
                ],
            [
                    'category_id' => 7,
                    'product_id' => 33,
                ],
            [
                    'category_id' => 7,
                    'product_id' => 34,
                ],
            [
                    'category_id' => 7,
                    'product_id' => 35,
                ],
            [
                    'category_id' => 7,
                    'product_id' => 36,
                ],
                // furniture

            [
                    'category_id' => 8,
                    'product_id' => 37,
                ],
            [
                    'category_id' => 8,
                    'product_id' => 38,
                ],
            [
                    'category_id' => 8,
                    'product_id' => 39,
                ],
            [
                    'category_id' => 8,
                    'product_id' => 40,
                ],
            [
                    'category_id' => 8,
                    'product_id' => 41,
                ],
            [
                    'category_id' => 8,
                    'product_id' => 42,
                ],

            [
                    'category_id' => 8,
                    'product_id' => 43,
                ],
            [
                    'category_id' => 8,
                    'product_id' => 44,
                ],
            [
                    'category_id' => 8,
                    'product_id' => 45,
                ],
            [
                    'category_id' => 8,
                    'product_id' => 46,
                ],
            [
                    'category_id' => 8,
                    'product_id' => 47,
                ],
            [
                    'category_id' => 8,
                    'product_id' => 48,
                ],
            [
                    'category_id' => 8,
                    'product_id' => 49,
                ],
                //phone & accessoire
            [
                    'category_id' => 9,
                    'product_id' => 50,
                ],
            [
                    'category_id' => 9,
                    'product_id' => 51,
                ],
            [
                    'category_id' => 9,
                    'product_id' => 52,
                ],
            [
                    'category_id' => 9,
                    'product_id' => 53,
                ],
            [
                    'category_id' => 9,
                    'product_id' => 54,
                ],
            [
                    'category_id' => 9,
                    'product_id' => 55,
                ],
            [
                    'category_id' => 9,
                    'product_id' => 56,
                ],
            [
                    'category_id' => 9,
                    'product_id' => 57,
                ],
            [
                    'category_id' => 9,
                    'product_id' => 58,
                ],
            [
                    'category_id' => 9,
                    'product_id' => 59,
                ],
            [
                    'category_id' => 9,
                    'product_id' => 60,
                ],
        ]);
    }
}